name: Excavator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次 UTC 00:00

jobs:
  excavate:
    name: 检查软件包更新
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: 配置Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: 检查更新
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
